Repository oracle/oci-volume-provisioner, pull requests merged in 2018-06, with the labels that each got.

#132 Stop retrying delete operations if volume does not exist
  pkg/provisioner/block/block.go
Labels: bug

#107 Append hyphen to volume name prefix
  pkg/provisioner/block/block.go
Labels: enhancement

#121 Round up volumes smaller than 50GB
  Makefile
  cmd/main.go
  pkg/oci/client/client.go
  pkg/oci/client/config_test.go
  pkg/provisioner/block/block.go
  pkg/provisioner/block/block_test.go
  pkg/provisioner/core/provisioner.go
Labels: enhancement

#139 Use failure-domain.beta.kubernetes.io/zone in match label examples
  README.md
  examples/example-claim-AD1.yaml
  examples/example-claim-AD2.yaml
  examples/example-claim-AD3.yaml
  examples/example-claim-from-backup.template
  examples/example-claim.template
Labels: documentation
